### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by Protogen3368** [SirOMGitsYOU/VicariousNetwork#4]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
4. See an error

**Expected behaviour**

**Screenshots**

**Logs**
If applicable, add latest.txt to help explain your problem.
[24/11/2020 00:31:30 AM] Started install of A Bit Of Everything version 3.8.4b [24/11/2020 00:31:33 AM] java.lang.NullPointerException at com.atlauncher.data.minecraft.loaders.forge.ForgeLoader.getMainClass(ForgeLoader.java:179) at com.atlauncher.workers.InstanceInstaller.determineMainClass(InstanceInstaller.java:590) at com.atlauncher.workers.InstanceInstaller.install(InstanceInstaller.java:416) at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:205) at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1) at javax.swing.SwingWorker$1.call(Unknown Source) at java.util.concurrent.FutureTask.run(Unknown Source) at javax.swing.SwingWorker.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source)

**Crash Reports**
If applicable, add crash-report.txt to help explain your problem.

**Modpack (please complete the following information):**
 - OS: [e.g. MacOS/Windows] Windows
 - Java Version [java -version in cmd] 1.8.0_271
- Modpack: [e.g ABOE}  ABOE
- Modpack Version: [e.g. 1.0.0] 3.8.4b

**Additional context**

**Comment by DrUltraLux** [comment]
This looks like an issue with AT Launcher not correctly installing/configuring it's Forge bootstrap.
You could try reinstalling AT Launcher, reinstalling the Modpack instance. If you still have problems, I'd contact AT launcher themselves about this. 

Alternatively Twitch/Overwolf or GD Launcher also have Vicarious Network Modpacks.

**Comment by SirOMGitsYOU** [comment]
No update from poster closing issue
